# Настройки Кирки Reverse

# Максимальное количество использований
max-uses: 1

# Материал кирки
pickaxe-material: GOLDEN_PICKAXE

# Отображаемое название (с поддержкой цветовых кодов)
display-name: "&x&A&9&0&0&F&F[&x&A&5&0&4&F&F♦&x&A&0&0&8&F&F] &x&9&7&1&0&F&FК&x&9&3&1&4&F&Fи&x&8&E&1&8&F&Fр&x&8&A&1&C&F&Fк&x&8&5&2&0&F&Fa &x&7&C&2&7&F&Fr&x&7&8&2&B&F&Fe&x&7&3&2&F&F&Fv&x&6&F&3&3&F&Fe&x&6&A&3&7&F&Fr&x&6&6&3&B&F&Fs&x&6&1&3&F&F&Fe"

# Описание предмета
lore:
  - "§7Специальная кирка для добычи спавнеров"
  - "§cПрочность: 1 использование"